import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  css: {
    modules: { localsConvention: 'camelCase' },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    css: true,
    include: [
      'src/features/auth/**/*.test.ts',
      'src/features/health/**/*.test.ts',
      'src/features/countdown/**/*.test.ts',
      'src/features/calendar/**/*.test.ts',
      'src/features/focus/**/*.test.{ts,tsx}',
      'src/services/cache/**/*.test.ts',
      'src/config/**/*.test.ts',
      'src/test/persist-verify.test.ts',
      'src/test/clawd-companion.test.ts',
      'src/test/context-menu-placement.test.ts',
      'src/test/clawd-placement.test.ts',
      'src/test/clawd-presentation-fallback.test.tsx',
      'src/store/usePetStore.test.ts',
      'src/store/useCharacterStore.test.ts',
      'src/store/useWallpaperStore.test.ts',
      'src/store/useHomeWidgetStore.test.ts',
      'src/store/agentIdentity.test.ts',
      'src/features/home/**/*.test.ts',
      'src/store/useHydrationStore.test.ts',
      'src/store/moonDietRetirement.test.ts',
      'src/components/journal/JournalQuickCaptureCard.test.tsx',
      'src/features/journal/**/*.test.{ts,tsx}',
      'src/features/agentActivity/**/*.test.{ts,tsx}',
      'src/features/clawdRuntime/**/*.test.ts',
      'src/features/clawdInteraction/**/*.test.ts',
      'src/features/clawdDrag/**/*.test.ts',
      'src/features/clawdMiniMode/**/*.test.ts',
      'src/features/clawdRest/**/*.test.ts',
      'src/features/clawdEyeTracking/**/*.test.ts',
      'src/features/clawdAssets/**/*.test.ts',
      'src/features/companionPets/**/*.test.ts',
      'src/features/clawdPerch/**/*.test.ts',
      'src/features/desktopPet/**/*.test.ts',
      'src/features/petAgentBridge/**/*.test.ts',
      'src/features/moonread/**/*.test.ts',
      'src/features/tideclock/**/*.test.ts',
      'src/features/exchange/**/*.test.ts',
      'src/features/typography/**/*.test.{ts,tsx}',
      'src/features/wallpaper/**/*.test.{ts,tsx}',
      'src/utils/**/*.test.ts',
      'src/features/period/**/*.test.ts',
      'src/features/apiUsage/**/*.test.ts',
      'src/features/lifeLedger/**/*.test.ts',
      'src/features/navigation/**/*.test.ts',
      'src/features/stash/**/*.test.ts',
      'src/features/moments/**/*.test.ts',
      'src/features/groupChat/**/*.test.{ts,tsx}',
      'src/store/groupChat.test.ts',
      'src/store/readReceipt.test.ts',
      'src/components/chat/SpeakerSheet.hooks.test.tsx',
      'src/components/settings/CalendarHolidaySettingsPanel.test.ts',
      'src/components/calendar/**/*.test.{ts,tsx}',
      'src/features/tidewatch/**/*.test.ts',
      'src/components/tidewatch/**/*.test.{ts,tsx}',
      'src/features/chat/**/*.test.ts',
      'src/ai/credentialStore.test.ts',
      'src/ai/credentialMigration.test.ts',
    ],
  },
});
