import { lazy, Suspense, useEffect, useState, type ComponentType, type ReactNode } from 'react';
import type { InteractiveAction, InteractiveAttachment, InteractiveKind, PollState, DiceState, DiceKind, DiceRollPhase, DiceTint, TimerState, GomokuState } from './types';
import { createGomokuState } from './gomokuAdapter';
import { GomokuInteractiveCard } from '@/components/chat/GomokuInteractiveCard';
import { saveAsset } from '@/store/assets';
import { useAssetBlobUrl } from '@/hooks/useAssetBlobUrl';
import { canManagePoll, canViewPollResults, canVoteInPoll, migrateLegacyPollCreator } from './pollAuthorization';

const DicePreview3D = lazy(() => import('./DicePreview3D').then((module) => ({ default: module.DicePreview3D })));

type ConfigProps = { onComplete: (attachment: InteractiveAttachment) => void; onCancel: () => void; creatorIdentityId?: string };
type RendererProps = { attachment: InteractiveAttachment; onAction: (action: InteractiveAction) => void; currentViewerIdentityId?: string; messageSenderIdentityId?: string };

const iconProps = { viewBox: '0 0 24 24', width: 22, height: 22, fill: 'none', stroke: 'currentColor', strokeWidth: 1.7, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, 'aria-hidden': true };
export function InteractiveIcon({ type }: { type: InteractiveKind }) {
  if (type === 'gomoku') return <svg {...iconProps}><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 3v18M12 3v18M17 3v18M3 7h18M3 12h18M3 17h18"/><circle cx="9.5" cy="9.5" r="2" fill="currentColor"/></svg>;
  if (type === 'poll') return <svg {...iconProps}><path d="M5 19V9M12 19V4M19 19v-7"/><path d="M3 19h18"/></svg>;
  if (type === 'dice') return <svg {...iconProps}><rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1" fill="currentColor"/><circle cx="16" cy="8" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="8" cy="16" r="1" fill="currentColor"/><circle cx="16" cy="16" r="1" fill="currentColor"/></svg>;
  return <svg {...iconProps}><circle cx="12" cy="13" r="8"/><path d="M12 9v5l3 2M9 2h6M12 2v3"/></svg>;
}

function envelope(kind: InteractiveKind, state: InteractiveAttachment['state']): InteractiveAttachment {
  return { version: 1, kind, state, meta: { gameId: crypto.randomUUID(), createdAt: Date.now(), startedBy: 'me' } };
}

function ConfigShell({ title, children, onCancel }: { title: string; children: ReactNode; onCancel: () => void }) {
  return <div className="interactive-config"><header><button type="button" onClick={onCancel} aria-label="返回互動工具">‹</button><h3>{title}</h3></header>{children}</div>;
}
function GomokuConfig({ onComplete, onCancel }: ConfigProps) {
  const [size, setSize] = useState<9 | 13 | 15>(15); const [first, setFirst] = useState<'black' | 'white'>('black');
  const state = () => createGomokuState(
    first === 'black' ? { kind: 'human', participantId: 'local-1', displayName: '黑方' } : { kind: 'human', participantId: 'local-2', displayName: '黑方' },
    first === 'white' ? { kind: 'human', participantId: 'local-1', displayName: '白方' } : { kind: 'human', participantId: 'local-2', displayName: '白方' }, size,
  );
  return <ConfigShell title="五子棋設定" onCancel={onCancel}><label>棋盤大小<select aria-label="棋盤大小" value={size} onChange={(e) => setSize(Number(e.target.value) as 9|13|15)}><option value="9">9 × 9</option><option value="13">13 × 13</option><option value="15">15 × 15</option></select></label><fieldset><legend>先後手</legend><label><input type="radio" checked={first==='black'} onChange={() => setFirst('black')}/> 我先手</label><label><input type="radio" checked={first==='white'} onChange={() => setFirst('white')}/> 我後手</label></fieldset><button type="button" className="pr-btn-confirm" onClick={() => onComplete(envelope('gomoku', state()))}>加入五子棋</button></ConfigShell>;
}
function PollConfig({ onComplete, onCancel, creatorIdentityId = 'me' }: ConfigProps) {
  const [question,setQuestion]=useState('');
  const [options,setOptions]=useState<Array<{id:string;label:string;imageAssetId?:string}>>([{id:crypto.randomUUID(),label:''},{id:crypto.randomUUID(),label:''}]);
  const [coverAssetId,setCoverAssetId]=useState<string>(); const [multiple,setMultiple]=useState(false); const [multipleLimit,setMultipleLimit]=useState(2);
  const [anonymous,setAnonymous]=useState(false); const [allowVoteChanges,setAllowVoteChanges]=useState(true);
  const [deadlineMode,setDeadlineMode]=useState<'none'|'day'|'custom'>('none'); const [customDeadline,setCustomDeadline]=useState('');
  const [resultVisibility,setResultVisibility]=useState<'immediate'|'after-close'|'creator-only'>('immediate');
  const [aiParticipation,setAiParticipation]=useState(false); const [aiVoteTiming,setAiVoteTiming]=useState<'immediate'|'after-user'|'before-close'>('after-user');
  const valid=Boolean(question.trim() && options.filter(x=>x.label.trim()).length>=2 && options.length<=12);
  const upload=async(file:File,onDone:(id:string)=>void)=>{if(!['image/png','image/webp','image/avif'].includes(file.type))return;onDone(await saveAsset(file,file.type));};
  const move=(from:number,to:number)=>setOptions(list=>{const next=[...list];const [item]=next.splice(from,1);next.splice(to,0,item);return next});
  const Switch=({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string})=><label className="poll-switch"><span>{label}</span><button type="button" role="switch" aria-label={label} aria-checked={checked} className={checked?'is-on':''} onClick={()=>onChange(!checked)}><i/></button></label>;
  return <ConfigShell title="建立投票" onCancel={onCancel}><div className="poll-composer">
    <label>問題<input aria-label="投票問題" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={160}/></label>
    <label className="poll-image-upload">投票封面<input type="file" accept="image/png,image/webp,image/avif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,setCoverAssetId)}}/><span>{coverAssetId?'已加入透明圖片':'選擇 PNG、WebP 或 AVIF'}</span></label>
    <div className="poll-options-editor">{options.map((option,index)=><div className="poll-option-editor" key={option.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData('text/plain')),index)}><span className="poll-drag-handle" aria-label="拖曳排序">⋮⋮</span><input aria-label={`投票選項 ${index+1}`} value={option.label} onChange={e=>setOptions(v=>v.map(x=>x.id===option.id?{...x,label:e.target.value}:x))}/><label className="poll-option-image"><input type="file" accept="image/png,image/webp,image/avif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,id=>setOptions(v=>v.map(x=>x.id===option.id?{...x,imageAssetId:id}:x)))}}/><span>{option.imageAssetId?'已加圖':'加圖'}</span></label><button type="button" aria-label={`刪除選項 ${index+1}`} disabled={options.length<=2} onClick={()=>setOptions(v=>v.filter(x=>x.id!==option.id))}>×</button></div>)}</div>
    {options.length<12&&<button type="button" className="poll-add-option" onClick={()=>setOptions(v=>[...v,{id:crypto.randomUUID(),label:''}])}>新增選項</button>}
    <div className="poll-settings-grid"><Switch checked={multiple} onChange={setMultiple} label="允許複選"/>{multiple&&<label>複選上限<select value={multipleLimit} onChange={e=>setMultipleLimit(Number(e.target.value))}>{Array.from({length:Math.max(1,options.length-1)},(_,i)=><option key={i+2} value={i+2}>{i+2}</option>)}</select></label>}<Switch checked={anonymous} onChange={setAnonymous} label="匿名投票"/><Switch checked={allowVoteChanges} onChange={setAllowVoteChanges} label="允許修改投票"/>
      <label>截止時間<select value={deadlineMode} onChange={e=>setDeadlineMode(e.target.value as typeof deadlineMode)}><option value="none">不限時</option><option value="day">24 小時</option><option value="custom">自訂</option></select></label>{deadlineMode==='custom'&&<label>自訂截止<input type="datetime-local" value={customDeadline} onChange={e=>setCustomDeadline(e.target.value)}/></label>}
      <label>結果可見性<select value={resultVisibility} onChange={e=>setResultVisibility(e.target.value as typeof resultVisibility)}><option value="immediate">立即顯示</option><option value="after-close">截止後顯示</option><option value="creator-only">建立者可見</option></select></label><Switch checked={aiParticipation} onChange={setAiParticipation} label="AI 成員參與"/>{aiParticipation&&<label>AI 投票時機<select value={aiVoteTiming} onChange={e=>setAiVoteTiming(e.target.value as typeof aiVoteTiming)}><option value="immediate">立即</option><option value="after-user">使用者投票後</option><option value="before-close">截止前</option></select></label>}
    </div>
    {aiParticipation&&aiVoteTiming==='before-close'&&<p className="poll-scheduler-note">需要背景排程；目前不會自動提交 AI 投票。</p>}
    <button type="button" className="pr-btn-confirm" disabled={!valid} onClick={()=>{const now=Date.now();const clean=options.filter(x=>x.label.trim()).map(x=>({...x,label:x.label.trim(),votes:0}));const expiresAt=deadlineMode==='day'?now+86400000:deadlineMode==='custom'&&customDeadline?new Date(customDeadline).getTime():undefined;const votesByIdentity=aiParticipation&&aiVoteTiming==='immediate'&&clean[0]?{'ai-lunaris':{optionIds:[clean[0].id],createdAt:now,updatedAt:now}}:{};const next=envelope('poll',{pollId:crypto.randomUUID(),creatorIdentityId,question:question.trim(),coverAssetId,options:clean,multiple,multipleLimit:multiple?Math.min(multipleLimit,clean.length):1,anonymous,allowVoteChanges,expiresAt,resultVisibility,aiParticipation,aiVoteTiming,votesByIdentity,votedOptionIds:[],settings:{anonymous,allowVoteChanges,resultVisibility,aiParticipation,aiVoteTiming}});next.meta.startedBy=creatorIdentityId;onComplete(next)}}>加入投票</button>
  </div></ConfigShell>;
}
function DiceConfig({ onComplete, onCancel }: ConfigProps) {
  const [quantity,setQuantity]=useState(1); const [kind,setKind]=useState<DiceKind>('d20'); const [customFaces,setCustomFaces]=useState(16); const [tint,setTint]=useState<DiceTint>('tide');
  const [previewResults,setPreviewResults]=useState<number[]>([]); const [previewKey,setPreviewKey]=useState(0); const [previewPhase,setPreviewPhase]=useState<DiceRollPhase>('idle');
  const kinds: Array<{ kind: DiceKind; label: string; faces: number }> = [{kind:'d4',label:'D4',faces:4},{kind:'d6',label:'D6',faces:6},{kind:'d8',label:'D8',faces:8},{kind:'d10',label:'D10',faces:10},{kind:'d12',label:'D12',faces:12},{kind:'d20',label:'D20',faces:20},{kind:'d24',label:'D24',faces:24},{kind:'d-percent',label:'D100 / %',faces:100},{kind:'custom',label:'Custom',faces:customFaces}];
  const tints: Array<{ value: DiceTint; label: string }> = [{value:'amber',label:'琥珀金'},{value:'tide',label:'月潮青'},{value:'ivory',label:'冷白'},{value:'midnight',label:'深藍黑'},{value:'violet',label:'粉紫'},{value:'coral',label:'珊瑚紅'}];
  const faces=kind==='custom'?customFaces:(kinds.find(item=>item.kind===kind)?.faces||20);
  const notation=kind==='d-percent'?`${quantity}d% (${quantity}d100)`:`${quantity}d${faces}`;
  const previewRolling=['launching','rolling','landing'].includes(previewPhase);
  useEffect(()=>{setPreviewResults([]);setPreviewPhase('idle')},[quantity,kind,faces]);
  return <div className="dice-configurator">
    <section className="dice-configurator__stage"><Suspense fallback={<div className="dice-preview-loading" role="status">載入 3D 骰子…</div>}><DicePreview3D kind={kind} faces={faces} tint={tint} quantity={quantity} results={previewResults} rollKey={previewKey} continuous={!previewResults.length} onPhaseChange={setPreviewPhase}/></Suspense><div className="dice-configurator__stage-label"><small>3D PREVIEW</small><strong>{notation}</strong>{previewResults.length>0&&!previewRolling&&<span>預覽結果：{previewResults.join(' · ')}</span>}</div></section>
    <section className="dice-settings-panel"><header><button type="button" className="dice-settings-back" onClick={onCancel} aria-label="返回互動工具">‹ 返回互動工具</button><h3>骰子</h3><p>配置一組適合這次冒險的多面骰。</p></header><div className="dice-settings-panel__scroll">
      <div className="dice-control-group"><span className="dice-control-label">數量</span><div className="dice-stepper"><button type="button" aria-label="減少骰子數量" onClick={()=>setQuantity(q=>Math.max(1,q-1))} disabled={quantity===1}>−</button><output aria-label="骰子數量">{quantity}</output><button type="button" aria-label="增加骰子數量" onClick={()=>setQuantity(q=>Math.min(20,q+1))} disabled={quantity===20}>+</button></div></div>
      <fieldset className="dice-control-group"><legend className="dice-control-label">骰種</legend><div className="dice-kind-grid">{kinds.map(item=><button type="button" key={item.kind} className={kind===item.kind?'is-active':''} aria-pressed={kind===item.kind} onClick={()=>setKind(item.kind)}>{item.label}</button>)}</div>{kind==='custom'&&<><label className="dice-custom-faces">自訂面數<input type="number" min="2" max="100" value={customFaces} onChange={e=>setCustomFaces(Math.max(2,Math.min(100,Number(e.target.value)||2)))} aria-label="自訂骰子面數"/></label><p className="dice-approximation-note">自訂骰體為視覺近似；結果 badge 為唯一可信結果。</p></>}</fieldset>
      <fieldset className="dice-control-group"><legend className="dice-control-label">色調</legend><div className="dice-tint-row">{tints.map(item=><button type="button" key={item.value} className={`dice-tint-chip is-${item.value}${tint===item.value?' is-active':''}`} aria-label={item.label} aria-pressed={tint===item.value} title={item.label} onClick={()=>setTint(item.value)}/>)}</div></fieldset>
      {kind==='d-percent'&&<p className="dice-percent-note">百分骰以 00、10、20…90 標示，正式結果範圍為 1–100。</p>}
      <div className="dice-summary"><span>目前配置</span><strong>{notation}</strong></div>
    </div><footer><button type="button" className="dice-configurator__trial" disabled={previewRolling} onClick={()=>{setPreviewResults(generateDiceResults(quantity,faces));setPreviewPhase('launching');setPreviewKey(key=>key+1)}}>{previewRolling?'試擲中…':'試擲'}</button><button type="button" className="pr-btn-confirm dice-configurator__cta" onClick={()=>{const timestamp=Date.now();onComplete(envelope('dice',{quantity,kind,sides:faces,faces,tint,results:[],total:0,createdBy:'你',timestamp,animationVersion:2,visualGeometryKind:kind,isVisualApproximation:!['d4','d6','d8','d12','d20'].includes(kind)}))}}>加入骰子</button></footer></section>
  </div>;
}
function TimerConfig({ onComplete, onCancel }: ConfigProps) {
  const [title,setTitle]=useState('倒數計時'); const [minutes,setMinutes]=useState(5);
  return <ConfigShell title="計時器設定" onCancel={onCancel}><label>標題<input aria-label="計時器標題" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>分鐘<input aria-label="計時分鐘" type="number" min="1" max="1440" value={minutes} onChange={e=>setMinutes(Math.max(1,Math.min(1440,Number(e.target.value))))}/></label><button type="button" className="pr-btn-confirm" onClick={()=>{const durationSeconds=minutes*60;onComplete(envelope('timer',{title:title.trim()||'倒數計時',durationSeconds,targetTimestamp:Date.now()+durationSeconds*1000,running:true}))}}>加入計時器</button></ConfigShell>;
}

function GomokuRenderer({ attachment,onAction }:RendererProps){return <GomokuInteractiveCard state={attachment.state as GomokuState} isParticipant onAction={state=>onAction({type:'gomoku_state',state})}/>}
function PollImage({assetId,className}:{assetId?:string;className:string}){const url=useAssetBlobUrl(assetId);return url?<img src={url} alt="" className={className}/>:null}
function PollRenderer({attachment,onAction,currentViewerIdentityId,messageSenderIdentityId}:RendererProps){const migrated=migrateLegacyPollCreator(attachment,messageSenderIdentityId);const s=migrated.state as PollState;const now=Date.now();const context={currentViewerIdentityId,messageSenderIdentityId,now};const expired=Boolean(s.expiresAt&&now>=s.expiresAt);const visible=canViewPollResults(s,context);const manageable=canManagePoll(s,context);const selected=s.votesByIdentity?.[currentViewerIdentityId||'']?.optionIds||[];return <div className="interactive-card poll-message-card" data-can-manage={manageable}>{s.coverAssetId&&<PollImage assetId={s.coverAssetId} className="poll-message-cover"/>}<h3>{s.question}</h3>{s.anonymous&&<small className="poll-anonymous-label">匿名投票</small>}{s.options.map(o=><button type="button" key={o.id} disabled={!canVoteInPoll(s,context)} className={selected.includes(o.id)?'is-selected':''} onClick={()=>currentViewerIdentityId&&onAction({type:'poll_vote',optionId:o.id,identityId:currentViewerIdentityId,now})}>{o.imageAssetId&&<PollImage assetId={o.imageAssetId} className="poll-option-thumb"/>}<span>{o.label}</span><small>{visible?`${o.votes} 票`:s.resultVisibility==='creator-only'?'僅建立者可見':'截止後顯示'}</small></button>)}{expired&&<p className="poll-closed">投票已截止</p>}</div>}
function DiceRenderer({attachment,onAction}:RendererProps){const s=attachment.state as DiceState;const quantity=s.quantity??s.count??1;const faces=s.faces??s.sides;const total=s.total??s.results.reduce((sum,value)=>sum+value,0);const [rolling,setRolling]=useState(false);const [expanded,setExpanded]=useState(false);const [rollKey,setRollKey]=useState(0);const startRoll=()=>{if(rolling)return;const results=generateDiceResults(quantity,faces);onAction({type:'dice_roll',results,now:Date.now()});setExpanded(true);setRolling(true);setRollKey(key=>key+1)};return <div className={`interactive-card dice-message-card is-${s.tint||'tide'}`}><div className="dice-message-card__head"><span className="dice-message-card__icon"><InteractiveIcon type="dice"/></span><div><h3>骰子</h3><strong>{quantity}d{faces}</strong></div></div>{expanded&&s.results.length>0&&<div className="dice-message-card__3d"><Suspense fallback={<div className="dice-preview-loading">載入 3D 骰子…</div>}><DicePreview3D kind={s.kind||'d6'} faces={faces} tint={s.tint||'tide'} quantity={quantity} results={s.results} rollKey={rollKey} continuous={false} onPhaseChange={phase=>{if(phase==='settled')setRolling(false)}}/></Suspense></div>}{!rolling&&<><div className="dice-results" aria-label="骰子結果">{s.results.length?s.results.map((value,index)=><span key={`${s.rolledAt||0}-${index}`}>{value}</span>):<em>尚未擲骰</em>}</div>{s.results.length>0&&<div className="dice-total"><span>Total</span><strong>{total}</strong></div>}</>}{s.isVisualApproximation&&<p className="dice-approximation-note">此骰體為視覺近似；結果 badge 為唯一可信結果。</p>}<div className="dice-message-card__foot"><small>操作者：{s.createdBy||'你'}</small><span className="dice-message-card__actions">{s.results.length>0&&!expanded&&<button type="button" onClick={()=>setExpanded(true)}>查看擲骰</button>}<button type="button" disabled={rolling} onClick={startRoll}>{rolling?'擲骰中…':s.results.length?'重新擲骰':'擲骰子'}</button></span></div></div>}
function TimerRenderer({attachment,onAction}:RendererProps){const s=attachment.state as TimerState;const [,tick]=useState(0);useEffect(()=>{if(!s.running)return;const id=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(id)},[s.running,s.targetTimestamp]);const remain=Math.max(0,Math.ceil((s.targetTimestamp-Date.now())/1000));return <div className="interactive-card"><h3>{s.title}</h3><div className="timer-value">{Math.floor(remain/60)}:{String(remain%60).padStart(2,'0')}</div><button type="button" onClick={()=>onAction({type:'timer_restart',now:Date.now()})}>重新開始</button></div>}

export interface InteractiveToolDefinition { type:InteractiveKind; label:string; description:string; schema:number; icon:ComponentType<{type:InteractiveKind}>; configurationComponent:ComponentType<ConfigProps>; messageRenderer:ComponentType<RendererProps>; initialStateFactory:()=>InteractiveAttachment; stateReducer:(attachment:InteractiveAttachment,action:InteractiveAction)=>InteractiveAttachment }
function randomInt(max:number){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
export function generateDiceResults(quantity:number,faces:number){return Array.from({length:quantity},()=>randomInt(faces)+1)}
export function reduceInteractiveAttachment(a:InteractiveAttachment,action:InteractiveAction):InteractiveAttachment{if(action.type==='gomoku_state'&&a.kind==='gomoku')return{...a,state:action.state};if(action.type==='poll_vote'&&a.kind==='poll'){const s=a.state as PollState;const now=action.now??Date.now();if(s.expiresAt&&now>=s.expiresAt)return a;const identity=action.identityId||'me';const votes={...(s.votesByIdentity||{})};const prior=votes[identity]?.optionIds??s.votedOptionIds??[];if(prior.length&&!s.allowVoteChanges)return a;const had=prior.includes(action.optionId);const ids=s.multiple?(had?prior.filter(id=>id!==action.optionId):[...prior,action.optionId]):(had?[]:[action.optionId]);if(s.multiple&&ids.length>(s.multipleLimit||s.options.length))return a;votes[identity]={optionIds:ids,createdAt:votes[identity]?.createdAt||now,updatedAt:now};if(s.aiParticipation&&s.aiVoteTiming==='after-user'&&identity!=='ai-lunaris'&&!votes['ai-lunaris']&&s.options[0])votes['ai-lunaris']={optionIds:[s.options[0].id],createdAt:now,updatedAt:now};return{...a,state:{...s,votesByIdentity:votes,votedOptionIds:ids,options:s.options.map(o=>({...o,votes:Object.values(votes).filter(v=>v?.optionIds.includes(o.id)).length}))}}}if(action.type==='dice_roll'&&a.kind==='dice'){const s=a.state as DiceState;const quantity=s.quantity??s.count??1;const faces=s.faces??s.sides;const results=action.results??generateDiceResults(quantity,faces);const now=action.now??Date.now();return{...a,state:{...s,quantity,kind:s.kind||'d6',sides:faces,faces,tint:s.tint||'tide',results,total:results.reduce((sum,value)=>sum+value,0),createdBy:s.createdBy||'你',timestamp:s.timestamp||now,rolledAt:now,animationVersion:2}}}if(action.type==='timer_restart'&&a.kind==='timer'){const s=a.state as TimerState;return{...a,state:{...s,targetTimestamp:action.now+s.durationSeconds*1000,running:true}}}return a}
const placeholder=()=>{const timestamp=Date.now();return envelope('dice',{quantity:1,kind:'d20',sides:20,faces:20,tint:'tide',results:[],total:0,createdBy:'你',timestamp})};
export const InteractiveToolRegistry:Record<InteractiveKind,InteractiveToolDefinition>={gomoku:{type:'gomoku',label:'五子棋',description:'本機雙人棋局',schema:1,icon:InteractiveIcon,configurationComponent:GomokuConfig,messageRenderer:GomokuRenderer,initialStateFactory:()=>envelope('gomoku',createGomokuState({kind:'human',participantId:'local-1',displayName:'黑方'},{kind:'human',participantId:'local-2',displayName:'白方'})),stateReducer:reduceInteractiveAttachment},poll:{type:'poll',label:'投票',description:'建立 2–12 個進階選項',schema:2,icon:InteractiveIcon,configurationComponent:PollConfig,messageRenderer:PollRenderer,initialStateFactory:()=>envelope('poll',{pollId:crypto.randomUUID(),question:'投票',options:[],multiple:false,votedOptionIds:[],votesByIdentity:{}}),stateReducer:reduceInteractiveAttachment},dice:{type:'dice',label:'骰子',description:'使用安全亂數擲骰',schema:1,icon:InteractiveIcon,configurationComponent:DiceConfig,messageRenderer:DiceRenderer,initialStateFactory:placeholder,stateReducer:reduceInteractiveAttachment},timer:{type:'timer',label:'計時器',description:'保存目標完成時間',schema:1,icon:InteractiveIcon,configurationComponent:TimerConfig,messageRenderer:TimerRenderer,initialStateFactory:()=>envelope('timer',{title:'倒數計時',durationSeconds:300,targetTimestamp:Date.now()+300000,running:true}),stateReducer:reduceInteractiveAttachment}};

export function InteractiveMessageRenderer({attachment,onChange,currentViewerIdentityId,messageSenderIdentityId}:{attachment:InteractiveAttachment;onChange:(next:InteractiveAttachment)=>void;currentViewerIdentityId?:string;messageSenderIdentityId?:string}){const migrated=migrateLegacyPollCreator(attachment,messageSenderIdentityId);const tool=InteractiveToolRegistry[migrated.kind];const Renderer=tool.messageRenderer;return <Renderer attachment={migrated} currentViewerIdentityId={currentViewerIdentityId} messageSenderIdentityId={messageSenderIdentityId} onAction={action=>onChange(tool.stateReducer(migrated,action))}/>}
