import { beforeEach, describe, expect, it } from 'vitest';
import { useReadingMemoryStore } from './useReadingMemoryStore';
describe('reading memory store',()=>{
  beforeEach(()=>{localStorage.clear();useReadingMemoryStore.getState().resetForTests()});
  it('undoes and redoes one committed image layer transform',()=>{const s=useReadingMemoryStore.getState();const id=s.createBoard();const asset='asset-a';const layer=s.addDecoration(id,{type:'image',assetId:asset,x:10,y:20,width:100,height:80,rotation:0,opacity:1,locked:false,aspectMode:'contain'});useReadingMemoryStore.getState().updateDecoration(id,layer,{x:250},true);expect(useReadingMemoryStore.getState().boards[0].imageLayers[0].x).toBe(250);useReadingMemoryStore.getState().undo();expect(useReadingMemoryStore.getState().boards[0].imageLayers[0].x).toBe(10);useReadingMemoryStore.getState().redo();expect(useReadingMemoryStore.getState().boards[0].imageLayers[0].x).toBe(250)});
  it('sorts timeline entries by explicit order and never array id',()=>{const id=useReadingMemoryStore.getState().createBoard();useReadingMemoryStore.getState().addEntry(id,{date:2,title:'B'});useReadingMemoryStore.getState().addEntry(id,{date:1,title:'A'});const entries=useReadingMemoryStore.getState().boards[0].entries;expect(new Set(entries.map(e=>e.id)).size).toBe(2);expect(entries.map(e=>e.order)).toEqual([0,1])});
  it('reorders layers and normalizes zIndex',()=>{const id=useReadingMemoryStore.getState().createBoard();const a=useReadingMemoryStore.getState().addDecoration(id,{type:'image',assetId:'a',x:0,y:0,width:10,height:10,rotation:0,opacity:1,locked:false,aspectMode:'contain'});const b=useReadingMemoryStore.getState().addDecoration(id,{type:'image',assetId:'b',x:0,y:0,width:10,height:10,rotation:0,opacity:1,locked:false,aspectMode:'free'});useReadingMemoryStore.getState().reorderDecoration(id,a,'top');const items=useReadingMemoryStore.getState().boards[0].imageLayers;expect(items.find(i=>i.id===a)?.zIndex).toBeGreaterThan(items.find(i=>i.id===b)!.zIndex)});
  it('creates a 750 by 1334 v2 board with canonical timeline and image layer fields',()=>{const id=useReadingMemoryStore.getState().createBoard();useReadingMemoryStore.getState().addEntry(id,{date:123,title:'漫畫足跡',author:'作者',excerpt:'摘記',moodTag:'沉浸',coverAssetId:'cover',chapterTitle:'第 2 話'});useReadingMemoryStore.getState().addDecoration(id,{type:'image',assetId:'page-shot',x:10,y:20,width:100,height:120,rotation:8,opacity:.8,flipX:true,flipY:false,locked:false,aspectMode:'free'});const board=useReadingMemoryStore.getState().boards[0];expect(board).toMatchObject({designWidth:750,designHeight:1334,templateId:'reading-timeline-v2'});expect(board.entries[0]).toMatchObject({date:123,excerpt:'摘記',moodTag:'沉浸',coverAssetId:'cover',chapterTitle:'第 2 話'});expect(board.imageLayers[0]).toMatchObject({assetId:'page-shot',aspectMode:'free',flipX:true})});
  it('migrates legacy decorations and timeline copy without losing asset references',async()=>{localStorage.setItem('lunartide-reading-memories-v1',JSON.stringify({version:1,state:{boards:[{id:'legacy',title:'舊足跡',templateId:'reading-timeline-v1',designWidth:750,designHeight:1334,entries:[{id:'entry',readAt:99,title:'舊書',note:'舊摘記',moodLabel:'平靜',order:0}],decorations:[{id:'image',type:'image',assetId:'kept-asset',x:1,y:2,width:30,height:40,rotation:0,opacity:1,zIndex:1,locked:false}],createdAt:1,updatedAt:1}]}}));await useReadingMemoryStore.persist.rehydrate();const board=useReadingMemoryStore.getState().boards[0];expect(board.entries[0]).toMatchObject({date:99,excerpt:'舊摘記',moodTag:'平靜'});expect(board.imageLayers[0]).toMatchObject({assetId:'kept-asset',aspectMode:'contain'});expect(board).not.toHaveProperty('decorations')});
});
