import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { chooseBotMove, playMove, type GomokuBoard, type Stone } from '@/features/playroom/gomokuEngine';
import { useGameSessionStore } from '@/store/useGameSessionStore';
import '@/styles/playroom-session.css';

export function GameSessionPage(){ const {sessionId=''}=useParams(); const nav=useNavigate(); const session=useGameSessionStore(s=>s.sessions[sessionId]); const update=useGameSessionStore(s=>s.updateSession); const checkpoint=useGameSessionStore(s=>s.checkpoint); const rollback=useGameSessionStore(s=>s.rollback); const pause=useGameSessionStore(s=>s.pauseSession); const [text,setText]=useState(''); const [panel,setPanel]=useState(false);
  useEffect(()=>{ if(session) useGameSessionStore.getState().setActive(session.id); },[session]); if(!session)return <Navigate to="/playroom" replace/>;
  const makeMove=(row:number,col:number)=>{ if(session.status==='completed')return; const state=session.publicState as {board:GomokuBoard;nextStone:Stone;winner:Stone|null;mode:string}; try { let result=playMove(state.board,{row,col},state.nextStone); let turn=session.currentTurn+1; let transcript=[...session.transcript,{id:crypto.randomUUID(),turn,actorSeatId:state.nextStone==='black'?'black':'white',kind:'action' as const,content:`${row+1},${col+1}`,createdAt:Date.now()}]; let next:Stone=state.nextStone==='black'?'white':'black'; if(!result.winner&&!result.draw&&next==='white'&&state.mode!=='local-duo'&&state.mode!=='model'){ const bot=chooseBotMove(result.board,(session.participants[1]?.botDifficulty||'standard')); const botResult=playMove(result.board,bot,'white'); result=botResult; turn++; transcript=[...transcript,{id:crypto.randomUUID(),turn,actorSeatId:'white',kind:'action',content:`${bot.row+1},${bot.col+1}`,createdAt:Date.now()}]; next='black'; } update(session.id,{currentTurn:turn,currentSeatId:next==='black'?'black':'white',status:result.winner||result.draw?'completed':'active',publicState:{...state,board:result.board,nextStone:next,winner:result.winner,draw:result.draw,summary:result.winner?`${result.winner==='black'?'黑棋':'白棋'}获胜`:result.draw?'和棋':undefined},transcript}); }catch{/* occupied cells remain inert */} };
  const submitStory=()=>{ if(!text.trim())return; const entries=[...((session.publicState.entries as string[])||[]),text.trim()]; const turn=session.currentTurn+1; update(session.id,{currentTurn:turn,publicState:{...session.publicState,entries},transcript:[...session.transcript,{id:crypto.randomUUID(),turn,actorSeatId:'player',kind:'dialogue',content:text.trim(),createdAt:Date.now()}]}); setText(''); };
  const isGomoku=session.gameDefinitionId==='gomoku'; const board=(session.publicState.board||[]) as GomokuBoard; return <main className="game-session"><header><Link to="/playroom">←</Link><div><span>LUNARIS PLAYROOM</span><h1>{session.title}</h1></div><button onClick={()=>setPanel(!panel)}>游戏信息</button></header><div className="game-session-layout"><section className="game-stage">{isGomoku?<><div className="gomoku-status">{session.publicState.winner?`${session.publicState.winner==='black'?'黑棋':'白棋'}获胜`:session.publicState.draw?'和棋':`轮到${session.publicState.nextStone==='black'?'黑棋':'白棋'}`}</div><div className="gomoku-board" role="grid" aria-label="五子棋棋盘">{board.map((r,row)=>r.map((cell,col)=><button key={`${row}-${col}`} role="gridcell" aria-label={`${row+1} 行 ${col+1} 列${cell?cell==='black'?'黑棋':'白棋':'空位'}`} onClick={()=>makeMove(row,col)} disabled={Boolean(cell)||session.status==='completed'}>{cell&&<span className={cell}/>}</button>))}</div></>:<><div className="story-world"><span>{String(session.publicState.narration)}</span><h2>{String(session.publicState.world)}</h2><p>序章已经展开。写下行动，重要的世界与角色状态会与文本分开保存。</p></div><div className="story-log">{(session.publicState.entries as string[]||[]).map((e,i)=><p key={i}>{e}</p>)}</div><div className="story-composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="描述行动或对话…"/><button onClick={submitStory}>推进故事</button></div></>}</section><aside className={panel?'is-open':''}><button className="panel-close" onClick={()=>setPanel(false)}>关闭</button><h2>参与者</h2>{session.participants.map(p=><div className="participant" key={p.seatId}><span>{p.displayName.slice(0,1)}</span><div><strong>{p.displayName}</strong><small>{p.participantType}</small></div></div>)}<h2>状态</h2><p>{session.status} · {session.currentTurn} 回合</p><h2>检查点</h2>{session.checkpoints.slice().reverse().map(c=><button className="checkpoint" key={c.id} onClick={()=>rollback(session.id,c.id)}>{c.label}</button>)}</aside></div><footer><button onClick={()=>checkpoint(session.id)}>建立检查点</button><button onClick={()=>pause(session.id)}>暂停</button>{isGomoku&&<button onClick={()=>nav('/playroom/new/gomoku')}>新开一局</button>}</footer></main>;
}
