import { useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { createBoard } from '@/features/playroom/gomokuEngine';
import { getGameDefinition } from '@/features/playroom/gameRegistry';
import type { GameParticipant } from '@/features/playroom/types';
import { useAppStore } from '@/store/useAppStore';
import { useGameSessionStore } from '@/store/useGameSessionStore';
import '@/styles/playroom-session.css';

const NARRATIONS = ['第一人称','第二人称','第三人称','小说模式','对话模式','游戏主持人模式'];
export function NewGamePage() { const { gameId='' } = useParams(); const [search] = useSearchParams(); const navigate=useNavigate(); const definition=getGameDefinition(gameId); const create=useGameSessionStore(s=>s.createSession); const providers=useAppStore(s=>s.providers); const contacts=useAppStore(s=>s.chatContacts); const [world,setWorld]=useState('月潮港'); const [player,setPlayer]=useState('旅人'); const [ai,setAi]=useState(contacts[0]?.name || '智能體'); const [narration,setNarration]=useState(NARRATIONS[0]); const [mode,setMode]=useState<'local-duo'|'bot-simple'|'bot-standard'|'model'>('bot-standard'); if(!definition||definition.status!=='playable') return <Navigate to="/playroom" replace/>;
  const start=()=>{ const linkedConversationId=search.get('conversationId')||undefined; let participants: GameParticipant[]; let publicState:Record<string,unknown>;
    if(gameId==='gomoku'){ participants=[{seatId:'black',participantType:'human',displayName:'我',connectionStatus:'local'},{seatId:'white',participantType:mode==='local-duo'?'human':mode==='model'?'model-agent':'local-bot',displayName:mode==='local-duo'?'玩家二':mode==='model'?ai:'本機 Bot',botDifficulty:mode==='bot-simple'?'simple':'standard',personaSnapshot:mode==='model'?{name:ai,personality:'聊天角色快照',speakingStyle:'保持当前角色语气'}:undefined,connectionStatus:'local'}]; publicState={board:createBoard(),nextStone:'black',winner:null,mode}; }
    else { participants=[{seatId:'player',participantType:'human',displayName:player,connectionStatus:'local'},{seatId:'narrator',participantType:'model-agent',displayName:ai,personaSnapshot:{name:ai,personality:'聊天角色快照',speakingStyle:'保持当前角色语气',providerId:providers[0]?.id,modelId:providers[0]?.model},providerId:providers[0]?.id,modelId:providers[0]?.model,connectionStatus:providers.length?'ready':'offline'}]; publicState={world,player,narration,worldState:{location:world,time:'序章'},characterState:{name:player,status:'准备出发'},entries:[],providerConfigured:providers.length>0}; }
    const s=create({gameDefinitionId:gameId,title:gameId==='gomoku'?`五子棋 · ${participants[1].displayName}`:`${world} · ${player}`,linkedConversationId,participants,publicState}); navigate(`/playroom/session/${s.id}`); };
  return <main className="game-setup"><Link to="/playroom">← 返回遊藝廳</Link><header><span>LUNARIS PLAYROOM</span><h1>新建{definition.title}</h1><p>设置会保存为本次游戏快照。</p></header>{gameId==='gomoku'?<section><label>对局模式<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="bot-standard">玩家 vs 标准 Bot</option><option value="bot-simple">玩家 vs 简单 Bot</option><option value="local-duo">本地双人轮流</option><option value="model">玩家 vs 聊天 AI</option></select></label>{mode==='model'&&<label>参与角色<input value={ai} onChange={e=>setAi(e.target.value)}/></label>}<p className="setup-note">真人在线联机将在未来版本提供。</p></section>:<section><label>1. 选择或创建世界<input value={world} onChange={e=>setWorld(e.target.value)}/></label><label>2. 玩家角色<input value={player} onChange={e=>setPlayer(e.target.value)}/></label><label>3. AI 角色<input value={ai} onChange={e=>setAi(e.target.value)}/></label><label>4. 叙事形式<select value={narration} onChange={e=>setNarration(e.target.value)}>{NARRATIONS.map(n=><option key={n}>{n}</option>)}</select></label><label>5. 模型<input value={providers[0]?.model||''} readOnly placeholder="尚未配置 AI 模型" /></label>{!providers.length&&<p className="setup-warning">尚未配置 AI 模型。请先前往设置，角色扮演不会静默启动。</p>}</section>}<button className="setup-start" onClick={start} disabled={gameId==='free-roleplay'&&!providers.length}>确认并开始</button>{gameId==='free-roleplay'&&!providers.length&&<Link className="setup-settings" to="/settings/ai">前往设置</Link>}</main>;
}
