import { beforeEach, describe, expect, it } from 'vitest';
import { requestTideRailAiDecision } from '@/features/tiderail/tideRailAdjudication';
import { useQuestStore } from '@/store/useQuestStore';
import { decideTideRailByPolicy, selectActiveMainline, useTideRailStore, validateTideRailDecision, type TideRailDecision, type TideRailProposal, type TideRailPriority } from '@/store/useTideRailStore';

const proposal = (id: string, priority: TideRailPriority = 'P2', patch: Partial<TideRailProposal> = {}): TideRailProposal => ({ id, projectId: 'lunartide', title: id, summary: `摘要 ${id}`, category: priority === 'P0' ? 'runtime_bug' : 'feature', priority, sourceRefs: [{ type: 'quest', id: `quest-${id}` }], impact: '真實影響', dependencies: [], acceptanceCriteria: ['驗收 A'], completedCriteria: [], firstAction: '先做第一步', sourceRoute: '/quests', started: false, status: 'advisory_open', createdAt: 1, updatedAt: 1, ...patch });
const decision = (verdict: TideRailDecision['verdict'], by: TideRailDecision['decidedBy'] = 'policy_engine', now = 10): TideRailDecision => ({ verdict, rationale: '公開且可追溯的理由', appliedRules: ['至少一條規則'], decidedBy: by, modelId: by === 'ai' ? 'test-model' : undefined, policyVersion: 'test-v1', decidedAt: now });

describe('TideRail advisory adjudication', () => {
  beforeEach(() => {
    localStorage.clear();
    useTideRailStore.setState({ proposals: [], activeMainlineProposalId: null, decisionLedger: [], adjudicationGeneration: {}, proposalInterruptionContracts: [], pausedProposalStack: [], mainlines: [], activeMainlineId: null, driftItems: [], interruptedStack: [], sessionClosures: [], isWindowOpen: false, activeTab: 'checkin', migrationVersion: 3 });
    useQuestStore.setState({ quests: [], mainQuestByDate: {}, questMigrationVersion: 1 });
  });
  it('allows only one active mainline proposal', () => { const a=proposal('a','P1');const b=proposal('b','P1');useTideRailStore.getState().syncProposals([a,b]);expect(useTideRailStore.getState().runPolicyAdjudication('a')).toMatchObject({verdict:'adopt'});expect(useTideRailStore.getState().runPolicyAdjudication('b')).toMatchObject({verdict:'require_interruption_contract'});expect(useTideRailStore.getState().activeMainlineProposalId).toBe('a') });
  it('saves a contract when P0 interrupts P2 and resumes after completion',()=>{useTideRailStore.getState().syncProposals([proposal('p2','P2',{category:'validation'}),proposal('p0','P0')]);useTideRailStore.getState().runPolicyAdjudication('p2');expect(useTideRailStore.getState().runPolicyAdjudication('p0')).toMatchObject({verdict:'require_interruption_contract'});expect(useTideRailStore.getState().confirmProposalInterruption('p0')).toBe(true);expect(useTideRailStore.getState().proposalInterruptionContracts).toHaveLength(1);useTideRailStore.setState((state)=>({proposals:state.proposals.map((item)=>item.id==='p0'?{...item,completedCriteria:['驗收 A']}:item)}));expect(useTideRailStore.getState().completeActiveProposal()).toBe(true);expect(useTideRailStore.getState().activeMainlineProposalId).toBe('p2')});
  it('does not let P3 replace an active P1',()=>expect(decideTideRailByPolicy(proposal('p3','P3'),proposal('p1','P1',{status:'adopted',started:true})))?.toMatchObject({verdict:'defer'}));
  it('does not convert support into automatic adoption',()=>{useTideRailStore.getState().syncProposals([proposal('a')]);expect(useTideRailStore.getState().voteProposal('a','support')).toBe(true);expect(useTideRailStore.getState().activeMainlineProposalId).toBeNull()});
  it('keeps opposition and rationale when AI still adopts',()=>{useTideRailStore.getState().syncProposals([proposal('a','P1')]);useTideRailStore.getState().voteProposal('a','oppose','不要擴張');const gen=useTideRailStore.getState().beginAdjudication('a')!;expect(useTideRailStore.getState().applyDecision('a',gen,decision('adopt','ai'))).toBe(true);expect(useTideRailStore.getState().proposals[0]).toMatchObject({userAdvisory:{vote:'oppose',reason:'不要擴張'},decision:{rationale:'公開且可追溯的理由'}})});
  it('adjudicates a proposal only once',()=>{useTideRailStore.getState().syncProposals([proposal('a')]);const gen=useTideRailStore.getState().beginAdjudication('a')!;expect(useTideRailStore.getState().applyDecision('a',gen,decision('defer'))).toBe(true);expect(useTideRailStore.getState().applyDecision('a',gen,decision('adopt'))).toBe(false)});
  it('rejects stale AI generations',()=>{useTideRailStore.getState().syncProposals([proposal('a')]);const old=useTideRailStore.getState().beginAdjudication('a')!;const latest=useTideRailStore.getState().beginAdjudication('a')!;expect(useTideRailStore.getState().applyDecision('a',old,decision('adopt','ai'))).toBe(false);expect(useTideRailStore.getState().applyDecision('a',latest,decision('defer','ai'))).toBe(true)});
  it('does not apply invalid schema',()=>{expect(validateTideRailDecision({verdict:'adopt',rationale:'x',appliedRules:[]},'ai')).toBeNull();expect(validateTideRailDecision({verdict:'magic',rationale:'x',appliedRules:['r']},'ai')).toBeNull()});
  it('does not fabricate AI decisions without a provider',async()=>{const result=await requestTideRailAiDecision(proposal('a'),null,[],new AbortController().signal);expect(result.decision).toBeNull();expect(result.error).toMatchObject({type:'not_configured',message:expect.stringContaining('尚未接入可用模型')})});
  it('distinguishes policy engine from AI decisions',()=>{expect(decision('defer').decidedBy).toBe('policy_engine');expect(decision('reject','ai').decidedBy).toBe('ai')});
  it('never activates superseded work',()=>expect(decideTideRailByPolicy(proposal('a','P1',{status:'superseded'}),null)).toBeNull());
  it('does not silently overwrite a started mainline',()=>{useTideRailStore.getState().syncProposals([proposal('a','P1',{started:true}),proposal('b','P1')]);useTideRailStore.getState().runPolicyAdjudication('a');const gen=useTideRailStore.getState().beginAdjudication('b')!;expect(useTideRailStore.getState().applyDecision('b',gen,decision('adopt','ai'))).toBe(false);expect(selectActiveMainline(useTideRailStore.getState())?.id).toBe('a')});
  it('persists votes and decisions across rehydrate',async()=>{useTideRailStore.getState().syncProposals([proposal('a','P1')]);useTideRailStore.getState().voteProposal('a','support','先修');useTideRailStore.getState().runPolicyAdjudication('a');const persisted=localStorage.getItem('lunartide-tiderail-v1')!;useTideRailStore.setState({proposals:[],activeMainlineProposalId:null,decisionLedger:[]});localStorage.setItem('lunartide-tiderail-v1',persisted);await useTideRailStore.persist.rehydrate();expect(useTideRailStore.getState().proposals[0]).toMatchObject({userAdvisory:{vote:'support',reason:'先修'},decision:{verdict:'adopt'}})});
  it('reuses one idempotent SystemQuest',()=>{const first=useQuestStore.getState().ensureSystemQuest('proposal-a',{title:'系統任務'});const second=useQuestStore.getState().ensureSystemQuest('proposal-a',{title:'系統任務'});expect(first).toBe(second);expect(useQuestStore.getState().quests).toHaveLength(1)});
  it('cannot complete a proposal before all acceptance criteria',()=>{useTideRailStore.getState().syncProposals([proposal('a','P1')]);useTideRailStore.getState().runPolicyAdjudication('a');expect(useTideRailStore.getState().completeActiveProposal()).toBe(false);useTideRailStore.setState((state)=>({proposals:state.proposals.map((item)=>({...item,completedCriteria:['驗收 A']}))}));expect(useTideRailStore.getState().completeActiveProposal()).toBe(true)});
});
