import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { ReviewRecord, TidewatchConsequence, TidewatchConsequencePreferences, TidewatchReviewPreferences } from './types';

const consequencePreferences: TidewatchConsequencePreferences = { intensity: 3, pool: [{ id: 'manual', title: '整理桌面', enabled: true, intensity: 1, executionType: 'manual', weight: 1, createdAt: 1, updatedAt: 1 }] };
const persisted = { preferences: undefined as TidewatchReviewPreferences | undefined, consequencePreferences: undefined as TidewatchConsequencePreferences | undefined, reviews: [] as ReviewRecord[], consequences: [] as TidewatchConsequence[] };
vi.mock('./repository', () => ({
  loadReviewPreferences: vi.fn(async () => persisted.preferences), loadAllReviewRecords: vi.fn(async () => [...persisted.reviews]), loadAllConsequences: vi.fn(async () => [...persisted.consequences]),
  loadConsequencePreferences: vi.fn(async () => persisted.consequencePreferences),
  saveReviewPreferences: vi.fn(async (value: TidewatchReviewPreferences) => { persisted.preferences = value; }),
  saveConsequencePreferences: vi.fn(async (value: TidewatchConsequencePreferences) => { persisted.consequencePreferences = value; }),
  saveReviewRecord: vi.fn(async (value: ReviewRecord) => { const index = persisted.reviews.findIndex((item) => item.id === value.id); if (index >= 0) persisted.reviews[index] = value; else persisted.reviews.push(value); }),
  saveConsequence: vi.fn(async (value: TidewatchConsequence) => { const sameSource = persisted.consequences.find((item) => item.sourceEventId === value.sourceEventId && item.id !== value.id); if (sameSource) throw new Error('duplicate'); const index = persisted.consequences.findIndex((item) => item.id === value.id); if (index >= 0) persisted.consequences[index] = value; else persisted.consequences.push(value); }),
}));

import { useTidewatchPolicyStore } from './reviewPolicyStore';

describe('canonical TIDEWATCH policy persistence', () => {
  beforeEach(() => { persisted.preferences = undefined; persisted.consequencePreferences = consequencePreferences; persisted.reviews = []; persisted.consequences = []; useTidewatchPolicyStore.setState({ preferences: { baseDifficulty: 2, difficultyMode: 'fixed', tone: 'restrained' }, consequencePreferences, reviews: [], consequences: [], hydrated: false }); });
  it('persists preferences and keeps the difficulty snapshot stable', async () => { await useTidewatchPolicyStore.getState().setPreferences({ baseDifficulty: 1, tone: 'master' }); const review = await useTidewatchPolicyStore.getState().submitReview({ questId: 'q', questTitle: '主線', requestType: 'defer', reason: '今天臨時增加必要家務，我會在晚餐後重新處理這項任務。' }); await useTidewatchPolicyStore.getState().setPreferences({ baseDifficulty: 5 }); expect(review.difficultySnapshot).toBe(1); expect(persisted.reviews[0].difficultySnapshot).toBe(1); });
  it('creates at most one consequence for one failure across reload', async () => { const first = await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 1); const second = await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 2); expect(second.id).toBe(first.id); expect(persisted.consequences).toHaveLength(1); useTidewatchPolicyStore.setState({ consequences: [], reviews: [], hydrated: false }); await useTidewatchPolicyStore.getState().hydrate(); expect(useTidewatchPolicyStore.getState().consequences).toHaveLength(1); });
  it('safety override leaves an audit record and fulfills risky consequences', async () => { await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 1); const audit = await useTidewatchPolicyStore.getState().safetyOverride({ questId: 'q', questTitle: '主線', reason: 'health', now: 2 }); expect(audit.decision.reasonCode).toBe('safety_override'); expect(useTidewatchPolicyStore.getState().consequences[0]).toMatchObject({ lifecycle: 'fulfilled', safetyOverride: 'health' }); });
  it('persists one selection across lifecycle and reload', async () => { const created = await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 1); const revealed = await useTidewatchPolicyStore.getState().resolveConsequence(created.id, () => 0, 2); expect(revealed).toMatchObject({ lifecycle: 'revealed', selectedItemId: 'manual', selectedAt: 2 }); await useTidewatchPolicyStore.getState().resolveConsequence(created.id, () => .9, 3); expect(persisted.consequences[0].selectedItemSnapshot?.title).toBe('整理桌面'); const active = await useTidewatchPolicyStore.getState().activateConsequence(created.id, 4); expect(active?.lifecycle).toBe('active'); const fulfilled = await useTidewatchPolicyStore.getState().fulfillConsequence(created.id, 5); expect(fulfilled).toMatchObject({ lifecycle: 'fulfilled', fulfilledAt: 5 }); useTidewatchPolicyStore.setState({ consequences: [], hydrated: false }); await useTidewatchPolicyStore.getState().hydrate(); expect(useTidewatchPolicyStore.getState().consequences[0].selectedItemId).toBe('manual'); });
  it('pool edits and deletion do not mutate a selected snapshot', async () => { const created = await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 1); await useTidewatchPolicyStore.getState().resolveConsequence(created.id, () => 0, 2); await useTidewatchPolicyStore.getState().upsertConsequencePoolItem({ ...consequencePreferences.pool[0], title: '改名' }); await useTidewatchPolicyStore.getState().deleteConsequencePoolItem('manual'); expect(useTidewatchPolicyStore.getState().consequences[0].selectedItemSnapshot?.title).toBe('整理桌面'); });
  it('persists date-scoped base override and feedback without changing pool weight', async () => { await useTidewatchPolicyStore.getState().useBaseDifficultyToday(new Date(2026, 8, 6)); expect(persisted.preferences?.useBaseDifficultyByDate?.['2026-09-06']).toBe(true); const created = await useTidewatchPolicyStore.getState().ensureConsequence('failure:q:1', 'q', '主線', 1); await useTidewatchPolicyStore.getState().resolveConsequence(created.id, () => 0, 2); await useTidewatchPolicyStore.getState().activateConsequence(created.id, 3); await useTidewatchPolicyStore.getState().fulfillConsequence(created.id, 4); await useTidewatchPolicyStore.getState().setConsequenceFeedback(created.id, 'too_heavy'); expect(persisted.consequences[0].perceivedIntensity).toBe('too_heavy'); expect(persisted.consequencePreferences?.pool[0].weight).toBe(1); });
});
