export type Stone = 'black' | 'white'; export type Cell = Stone | null; export type GomokuBoard = Cell[][];
export interface Move { row: number; col: number }
export const BOARD_SIZE = 15;
export const createBoard = (): GomokuBoard => Array.from({ length: BOARD_SIZE }, () => Array<Cell>(BOARD_SIZE).fill(null));
export const legalMoves = (board: GomokuBoard): Move[] => board.flatMap((row, r) => row.map((cell, c) => cell === null ? { row: r, col: c } : null).filter((x): x is Move => Boolean(x)));
export function winnerAt(board: GomokuBoard, move: Move): Stone | null { const stone = board[move.row]?.[move.col]; if (!stone) return null; for (const [dr, dc] of [[1,0],[0,1],[1,1],[1,-1]]) { let count = 1; for (const sign of [-1, 1]) for (let n = 1; n < 5; n++) { if (board[move.row + dr*n*sign]?.[move.col + dc*n*sign] !== stone) break; count++; } if (count >= 5) return stone; } return null; }
export function playMove(board: GomokuBoard, move: Move, stone: Stone) { if (!Number.isInteger(move.row) || !Number.isInteger(move.col) || board[move.row]?.[move.col] !== null) throw new Error('ILLEGAL_MOVE'); const next = board.map((row) => [...row]); next[move.row][move.col] = stone; return { board: next, winner: winnerAt(next, move), draw: legalMoves(next).length === 0 }; }
const lines = (board: GomokuBoard, move: Move, stone: Stone) => { const next = board.map(r => [...r]); next[move.row][move.col] = stone; return winnerAt(next, move) === stone; };
export function chooseBotMove(board: GomokuBoard, difficulty: 'simple' | 'standard' = 'standard'): Move { const moves = legalMoves(board); if (!moves.length) throw new Error('NO_LEGAL_MOVES'); for (const stone of ['white','black'] as Stone[]) { const decisive = moves.find(m => lines(board, m, stone)); if (decisive) return decisive; } if (difficulty === 'simple') return moves[Math.floor(Math.random() * moves.length)]; return moves.sort((a,b) => (Math.abs(a.row-7)+Math.abs(a.col-7))-(Math.abs(b.row-7)+Math.abs(b.col-7)))[0]; }
export function validateModelMove(board: GomokuBoard, candidate: unknown): Move | null { if (!candidate || typeof candidate !== 'object') return null; const { row, col } = candidate as Move; return legalMoves(board).some(m => m.row === row && m.col === col) ? { row, col } : null; }
