import { useEffect,useMemo,useRef,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import { useMoonReadStore } from '@/features/moonread/useMoonReadStore';
import { useAssetBlobUrl } from '@/hooks/useAssetBlobUrl';
import { useComicPageUrls } from '@/features/moonread/comic/useComicPageUrls';
import type { ComicPage,ComicReadingMode } from '@/features/moonread/types';
import { arrowPageDelta } from '@/features/moonread/comic/runtime';
import '@/styles/comic-reader.css';
export function ComicReaderPage(){const {bookId}=useParams();const navigate=useNavigate();const book=useMoonReadStore(s=>s.books.find(item=>item.id===bookId));const saved=useMoonReadStore(s=>bookId?s.comicProgress[bookId]:undefined);const allNotes=useMoonReadStore(s=>s.comicAnnotations);const update=useMoonReadStore(s=>s.updateComicProgress);const addNote=useMoonReadStore(s=>s.addComicAnnotation);const comic=book?.comic;const [page,setPage]=useState(saved?.pageIndex||0);const [mode,setMode]=useState<ComicReadingMode>(saved?.mode||comic?.defaultReadingMode||'single');const [fit,setFit]=useState<'width'|'height'|'original'>('height');const [notesOpen,setNotesOpen]=useState(false);const [thumbs,setThumbs]=useState(false);const [text,setText]=useState('');const touch=useRef<number|undefined>(undefined);const urls=useComicPageUrls(comic?.pages||[],page,2);const notes=useMemo(()=>allNotes.filter(note=>note.bookId===bookId&&note.pageIndex===page),[allNotes,bookId,page]);
useEffect(()=>{if(bookId&&comic){update({bookId,pageIndex:page,mode,direction:comic.direction,updatedAt:Date.now()});}},[bookId,page,mode,comic?.direction]);useEffect(()=>{if(!comic)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft')step(arrowPageDelta(e.key,comic.direction));};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[comic,page]);
if(!book||!comic)return <div className="comic-reader-empty">找不到漫畫</div>;const step=(delta:number)=>setPage(value=>Math.max(0,Math.min(comic.pageCount-1,value+delta)));const semanticNext=()=>step(1);const semanticPrev=()=>step(-1);const progress=Math.round(((page+1)/comic.pageCount)*100);
return <div className="comic-reader" data-testid="comic-reader"><header className="comic-toolbar"><button onClick={()=>navigate('/moonread')}>‹ 書架</button><div><strong>{book.title}</strong><span>第 {page+1} / {comic.pageCount} 頁 · {progress}%</span></div><button onClick={()=>setThumbs(v=>!v)}>縮圖</button><select aria-label="閱讀模式" value={mode} onChange={e=>setMode(e.target.value as ComicReadingMode)}><option value="single">單頁</option><option value="continuous">連續</option></select><button onClick={()=>setNotesOpen(v=>!v)}>批註</button></header><main className="comic-layout">{thumbs&&<ComicThumbnailRail pages={comic.pages} current={page} onSelect={setPage}/>} {mode==='single'?<section className="comic-single" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-(touch.current||0);if(Math.abs(dx)>45)(dx<0)===(comic.direction==='ltr')?semanticNext():semanticPrev();}}><button aria-label="上一頁" onClick={semanticPrev}>‹</button><img data-testid="comic-page" className={`fit-${fit}`} src={urls[page]} alt={`第 ${page+1} 頁`}/><button aria-label="下一頁" onClick={semanticNext}>›</button></section>:<ComicContinuousReader pages={comic.pages} current={page} onCurrent={setPage}/>} {notesOpen&&<aside className="comic-notes"><header><strong>第 {page+1} 頁批註</strong><button onClick={()=>setNotesOpen(false)}>×</button></header>{notes.map(note=><p key={note.id}>{note.content}</p>)}<textarea aria-label="頁面批註" value={text} onChange={e=>setText(e.target.value)}/><button disabled={!text.trim()} onClick={()=>{addNote({bookId:book.id,pageIndex:page,authorType:'user',content:text.trim()});setText('');}}>新增批註</button><button onClick={()=>alert(`將只傳送第 ${page+1} 頁；Vision provider 尚未設定。`)}>讓 LUNARIS 看這一頁</button></aside>}</main><footer className="comic-bottom"><button onClick={semanticPrev}>上一頁</button><button onClick={()=>setFit(fit==='height'?'width':fit==='width'?'original':'height')}>{fit==='height'?'Fit Height':fit==='width'?'Fit Width':'Original'}</button><button onClick={semanticNext}>下一頁</button></footer></div>}
function ComicThumbnailRail({pages,current,onSelect}:{pages:ComicPage[];current:number;onSelect:(index:number)=>void}){return <nav className="comic-thumbs" aria-label="漫畫縮圖">{pages.map(page=><Thumbnail key={page.id} page={page} active={page.index===current} onClick={()=>onSelect(page.index)}/>)}</nav>}
function Thumbnail({page,active,onClick}:{page:ComicPage;active:boolean;onClick:()=>void}){const ref=useRef<HTMLButtonElement>(null);const [near,setNear]=useState(active);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))setNear(true)},{rootMargin:'200px 0px'});observer.observe(node);return()=>observer.disconnect()},[]);const url=useAssetBlobUrl(near?page.assetId:undefined);return <button ref={ref} className={active?'active':''} onClick={onClick}>{url&&<img src={url} alt=""/>}<span>{page.index+1}</span></button>}
function ComicContinuousReader({pages,current,onCurrent}:{pages:ComicPage[];current:number;onCurrent:(index:number)=>void}){return <section className="comic-continuous">{pages.map(page=><LazyPage key={page.id} page={page} active={page.index===current} onVisible={()=>onCurrent(page.index)}/>)}</section>}
function LazyPage({page,active,onVisible}:{page:ComicPage;active:boolean;onVisible:()=>void}){const ref=useRef<HTMLDivElement>(null);const [near,setNear]=useState(false);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){setNear(true);onVisible();}}),{rootMargin:'120% 0px'});observer.observe(node);return()=>observer.disconnect();},[]);const url=useAssetBlobUrl(near?page.assetId:undefined);return <div ref={ref} className={active?'active':''} style={{aspectRatio:`${page.width||2}/${page.height||3}`}}>{url&&<img src={url} loading="lazy" alt={`第 ${page.index+1} 頁`}/>}</div>}
